apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    {{- include "insurance-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "insurance-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insurance-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env: 
            {{- range $key, $val := .Values.ENV }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
            {{- range $key, $val := .Values.SECRETS }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: global-connect-secrets
                  key: {{ $key }}
            {{- end}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
