
const STATUS_CODES = {
  'WIP': 0,
  'Submission': 10,
  'Quote': 20,
  'Bind': 30,
  'Post Bind': 40
}

const WIP_REQUIREMENT = []
  // "submission_txt",
  // "insured_name",
  // "effective_dt",
  // "expiration_dt",
  // "country_id",
  // "carrier_id",
  // "policy_id",
  // "lob_id",
  // "product_txt",
  // "limit1_id",
  // "limit1_amt",
  // "retention1_id",
  // "retention1_amt",
  // "attach_amt",
  // "share_amt",
// ]

const SUBMISSION_REQUIREMENT = [
  "submission_txt",
  "insured_name",
  "effective_dt",
  "expiration_dt",
  "country_id",
  "carrier_id",
  "policy_id",
  "lob_id",
  "product_txt",
  "limit1_id",
  "limit1_amt",
  "retention1_id",
  "retention1_amt",
  "attach_amt",
  "share_amt",
  "underwriter_id",
  "ripremium_amt",
  "ricommision_amt",
  "riattach_amt",
  "rilimit_amt",
  "riretention_amt",
  "rishare_amt",
  "location_id",
  "location_address",
  "sic_id",
  "basis_id",
  "exposure_amt",
  "order_nbr",
  "form_txt",
  "name_txt",
  "description_txt",
  "schedule_txt",
]
  
  
const QUOTE_REQUIREMENT = [
  "submission_txt",
  "insured_name",
  "effective_dt",
  "expiration_dt",
  "country_id",
  "carrier_id",
  "policy_id",
  "lob_id",
  "product_txt",
  "limit1_id",
  "limit1_amt",
  "retention1_id",
  "retention1_amt",
  "attach_amt",
  "share_amt",
  "underwriter_id",
  "ripremium_amt",
  "ricommision_amt",
  "riattach_amt",
  "rilimit_amt",
  "riretention_amt",
  "rishare_amt",
  "location_id",
  "location_address",
  "sic_id",
  "basis_id",
  "exposure_amt",
  "order_nbr",
  "form_txt",
  "name_txt",
  "description_txt",
  "schedule_txt",
  "insured_address",
  "carrier_address",
  "broker_id",
  "broker_address",
  "gross_amt",
  "commission_amt",
  "security_amt",
  "tpa_id",
  "authority_amt",
]
  
  
const BIND_REQUIREMENT = [
  "submission_txt",
  "insured_name",
  "effective_dt",
  "expiration_dt",
  "country_id",
  "carrier_id",
  "policy_id",
  "lob_id",
  "product_txt",
  "limit1_id",
  "limit1_amt",
  "retention1_id",
  "retention1_amt",
  "attach_amt",
  "share_amt",
  "underwriter_id",
  "ripremium_amt",
  "ricommision_amt",
  "riattach_amt",
  "rilimit_amt",
  "riretention_amt",
  "rishare_amt",
  "location_id",
  "location_address",
  "sic_id",
  "basis_id",
  "exposure_amt",
  "order_nbr",
  "form_txt",
  "name_txt",
  "description_txt",
  "schedule_txt",
  "insured_address",
  "carrier_address",
  "broker_id",
  "broker_address",
  "gross_amt",
  "commission_amt",
  "security_amt",
  "tpa_id",
  "authority_amt",
  "riskmanager_id",
  "prefix_txt",
  "policy_txt",
  "suffix_txt",
  "ripolicy_txt",
  "billtype_id",
  "roe_dt",
]
  
  
const POST_BIND_REQUIREMENT = [
  "submission_txt",
  "insured_name",
  "effective_dt",
  "expiration_dt",
  "country_id",
  "carrier_id",
  "policy_id",
  "lob_id",
  "product_txt",
  "limit1_id",
  "limit1_amt",
  "retention1_id",
  "retention1_amt",
  "attach_amt",
  "share_amt",
  "underwriter_id",
  "ripremium_amt",
  "ricommision_amt",
  "riattach_amt",
  "rilimit_amt",
  "riretention_amt",
  "rishare_amt",
  "location_id",
  "location_address",
  "sic_id",
  "basis_id",
  "exposure_amt",
  "order_nbr",
  "form_txt",
  "name_txt",
  "description_txt",
  "schedule_txt",
  "insured_address",
  "carrier_address",
  "broker_id",
  "broker_address",
  "gross_amt",
  "commission_amt",
  "security_amt",
  "tpa_id",
  "authority_amt",
  "riskmanager_id",
  "prefix_txt",
  "policy_txt",
  "suffix_txt",
  "ripolicy_txt",
  "billtype_id",
  "roe_dt",
  "producer_id",
  "tax_amt",
  "fee_amt",
  "surcharge_amt",
]
  

module.exports = { STATUS_CODES, WIP_REQUIREMENT, SUBMISSION_REQUIREMENT, QUOTE_REQUIREMENT, BIND_REQUIREMENT, POST_BIND_REQUIREMENT }